name: CI

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2    
    - name: ls -alF
      run: |
        ls -alF
        pwd
